version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: weather
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
      # Copy CSV file to /mysql-files directory in MySQL container
      # and mount that directory to /docker-entrypoint-initdb.d/
      # instead of the /data directory
      # - ./data/weather.csv:/mysql-files/weather.csv
